spring:
  datasource:
    druid:
      username: root
      password: luc123456
      url: jdbc:mysql://localhost:3306/mini_app_cookbook?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=FALSE


# 对象存储配置
file:
  storage:
    enabled: true
    oss:
      enabled: true
      # ak
      access-key: OdhEzyfQYOfuiy2Z2tPLCbIRM94pJafqO4B_X3Fb
      # sk
      secret-key: 3BUT6Iq8YLyfL13fRd0vHxR6_Z9L1EaxPvv_fZDk
      default-bucket-name: mini-program-cookbook
      default-domain-of-bucket: qiniucs.com
      buckets:
        - name: mini-program-cookbook
          region: cn-south-1
          use-https: true
          path-style-enabled: false