sys:
  security:
    # 前端登录页面地址, 前后端分离项目用绝对地址http://localhost/login
    login-page: http://127.0.0.1/#/login?redirect=/dashboard
    # 后端登录接口
    login-api: /login
    # 白名单
    white-paths:
      - /v3/api-docs/**
      - /swagger-ui/**
      - /swagger-resources/**
      - /doc.html
      - /favicon.ico
      - /login
      - /index
      - /captcha
  cors:
    enabled: true
    allow-credentials: true
    allowed-origin-patterns: "*"
    allowed-methods:
      - GET
      - HEAD
      - PUT
      - POST
      - PATCH
      - DELETE
      - OPTIONS
      - TRACE
    allowed-headers:
      - "Authorization"
      - "Authentication"
      - "X-Refresh-Token"
      - "X-Access-Token"