#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    tags-sorter: alpha
#    operations-sorter: alpha
#    show-extensions: true
#  api-docs:
#    path: /v3/api-docs
#    enabled: true
#  group-configs:
#    - group: "default"
#      paths-to-match: '/**'
#      packages-to-scan: com.lc.authorization.server
#  default-flat-param-object: false
#knife4j:
#  enable: true
#  setting:
#    enable-swagger-models: true